"""
Adobe After Effects Track & CornerPin Exporter
==============================================
Exports point tracking and planar CornerPin data to JSON and Adobe ExtendScript (.jsx).
"""

import os
import json
from typing import List, Dict, Any


class AfterEffectsExporter:
    """Exports motion trajectories to After Effects compatible formats."""

    @staticmethod
    def export_json(
        tracks: List[Dict[str, Any]],
        output_json_path: str,
        composition_w: int = 1920,
        composition_h: int = 1080
    ) -> str:
        """
        Exports standardized JSON data format readable by AE scripts.
        """
        ae_data = {
            "application": "Adobe After Effects",
            "version": "1.0",
            "comp_width": composition_w,
            "comp_height": composition_h,
            "keyframe_count": len(tracks),
            "tracks": []
        }

        for pt in tracks:
            f = pt.get("frame", pt.get("t", 0))
            x = pt.get("x", 0.5) * composition_w
            y = pt.get("y", 0.5) * composition_h
            conf = pt.get("confidence", 1.0)

            ae_data["tracks"].append({
                "frame": f,
                "position": [round(x, 2), round(y, 2)],
                "confidence": round(conf, 3)
            })

        os.makedirs(os.path.dirname(os.path.abspath(output_json_path)), exist_ok=True)
        with open(output_json_path, "w", encoding="utf-8") as f:
            json.dump(ae_data, f, indent=2)

        return output_json_path

    @staticmethod
    def export_jsx(
        tracks: List[Dict[str, Any]],
        output_jsx_path: str,
        composition_w: int = 1920,
        composition_h: int = 1080,
        layer_name: str = "Tracked_Null"
    ) -> str:
        """
        Generates an Adobe ExtendScript (.jsx) file to create and keyframe a Null Layer in AE.
        """
        lines = [
            "// After Effects ExtendScript Matchmove Keyframer",
            "// Generated by Tracker Motion Studio",
            "app.beginUndoGroup('Apply Motion Track');",
            "var comp = app.project.activeItem;",
            "if (comp && comp instanceof CompItem) {",
            f"    var nullLayer = comp.layers.addNull();",
            f"    nullLayer.name = '{layer_name}';",
            "    var posProp = nullLayer.property('Position');",
            ""
        ]

        for pt in tracks:
            f = pt.get("frame", pt.get("t", 0))
            x = pt.get("x", 0.5) * composition_w
            y = pt.get("y", 0.5) * composition_h
            # Convert frame to seconds
            t_sec = f / 30.0 if isinstance(f, (int, float)) and f > 1.0 else f
            lines.append(f"    posProp.setValueAtTime({t_sec:.3f}, [{x:.2f}, {y:.2f}]);")

        lines.extend([
            "",
            "    alert('✅ Motion Track Keyframes applied to Null Layer!');",
            "}",
            "app.endUndoGroup();"
        ])

        os.makedirs(os.path.dirname(os.path.abspath(output_jsx_path)), exist_ok=True)
        with open(output_jsx_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return output_jsx_path
