"""
Blender 3D Camera & Scene Exporter
==================================
Generates standalone Python scripts for Blender (.py) to automatically create
animated 3D Camera objects matching solved matchmove trajectories.
"""

import os
from typing import List, Dict, Any, Optional


class BlenderExporter:
    """Exports solved camera trajectories to Blender Python scripts."""

    @staticmethod
    def export_camera_script(
        trajectory: List[Dict[str, Any]],
        output_py_path: str,
        fps: float = 30.0,
        focal_length_mm: float = 35.0,
        sensor_width_mm: float = 36.0
    ) -> str:
        """
        Writes a Python script that can be run inside Blender's Scripting workspace.
        Creates a 'Matchmove_Camera' with keyframed location and rotation.
        """
        lines = [
            "# ==========================================================",
            "# Blender Matchmove Camera Import Script",
            "# Generated by Tracker Motion Studio (AI-Operable VFX Core)",
            "# ==========================================================",
            "import bpy",
            "import math",
            "",
            "# 1. Setup Scene Settings",
            "scene = bpy.context.scene",
            f"scene.render.fps = {int(round(fps))}",
            f"scene.frame_start = 0",
            f"scene.frame_end = {max(1, len(trajectory) - 1)}",
            "",
            "# 2. Create Matchmove Camera",
            "cam_data = bpy.data.cameras.new(name='Matchmove_Cam_Data')",
            f"cam_data.lens = {focal_length_mm}",
            f"cam_data.sensor_width = {sensor_width_mm}",
            "cam_obj = bpy.data.objects.new('Matchmove_Camera', cam_data)",
            "bpy.context.collection.objects.link(cam_obj)",
            "scene.camera = cam_obj",
            "",
            "# 3. Keyframe Animation Trajectory",
            "cam_obj.animation_data_create()",
            "cam_obj.animation_data.action = bpy.data.actions.new(name='Camera_Solve_Action')",
            ""
        ]

        for pt in trajectory:
            frame = pt.get("frame", 0)
            dx = pt.get("dx", 0.0)
            dy = pt.get("dy", 0.0)
            da = pt.get("da", 0.0)
            zoom = pt.get("zoom", 1.0)

            # Map 2D/3D affine to Blender 3D space (Z up, -Y forward)
            # Scaling coordinates for Blender metric units
            bl_x = dx * 0.01
            bl_y = -(zoom - 1.0) * 10.0
            bl_z = -dy * 0.01
            rot_z = da

            lines.append(f"# Frame {frame}")
            lines.append(f"scene.frame_set({frame})")
            lines.append(f"cam_obj.location = ({bl_x:.4f}, {bl_y:.4f}, {bl_z:.4f})")
            lines.append(f"cam_obj.rotation_euler = (math.radians(90), 0, {rot_z:.5f})")
            lines.append("cam_obj.keyframe_insert(data_path='location', frame=" + str(frame) + ")")
            lines.append("cam_obj.keyframe_insert(data_path='rotation_euler', frame=" + str(frame) + ")")
            lines.append("")

        lines.append("print('✅ Matchmove Camera imported successfully into Blender!')")

        os.makedirs(os.path.dirname(os.path.abspath(output_py_path)), exist_ok=True)
        with open(output_py_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return output_py_path
